version: '3.3'
services:
    expose:
        image: registry.wimark.tk/expose:latest
        environment:
          MONGO_ADDR: db
          SERVE_ADDR: :8081
        restart: always
        entrypoint: /expose
        logging:
          driver: "json-file"
          options:
            max-size: "50m"
        network_mode: host
